workflows:
  android-workflow:
    name: Rahab Quran - Android Build
    instance_type: mac_mini_m2
    
    environment:
      java: 17
      
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x gradlew
      
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/apk/**/*.apk
